/*
Navicat MySQL Data Transfer

Source Server         : localhost_3306
Source Server Version : 50516
Source Host           : localhost:3306
Source Database       : mydealfo_deal

Target Server Type    : MYSQL
Target Server Version : 50516
File Encoding         : 65001

Date: 2014-04-01 16:47:53
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `cd_category_new`
-- ----------------------------
DROP TABLE IF EXISTS `cd_category_new`;
CREATE TABLE `cd_category_new` (
  `i_id` int(11) NOT NULL AUTO_INCREMENT,
  `s_category` varchar(255) NOT NULL,
  `i_status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '1->Active,0->Inactive',
  `s_meta_title` varchar(255) NOT NULL,
  `s_meta_description` text NOT NULL,
  `s_meta_keyword` varchar(255) NOT NULL,
  `s_image` varchar(255) NOT NULL,
  `s_url` varchar(255) NOT NULL,
  `s_thumb` varchar(255) NOT NULL DEFAULT 'no-image.png',
  `i_parent_id` int(11) NOT NULL DEFAULT '0',
  `e_show_in_frontend` enum('0','1','2') NOT NULL DEFAULT '0' COMMENT '0=> hide from fron end 1 => to deal 2 =>to coupon',
  `i_total_product` bigint(30) NOT NULL DEFAULT '0',
  PRIMARY KEY (`i_id`)
) ENGINE=InnoDB AUTO_INCREMENT=390 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of cd_category_new
-- ----------------------------
INSERT INTO `cd_category_new` VALUES ('1', 'Mobiles & Tablets', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('2', 'Computers & Accessories', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('3', 'Books & Magazines', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('4', 'Consumer Electronics', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('5', 'Cameras', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('6', 'Gifts', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('7', 'Fashion & Accessories', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('8', 'Baby Care & Toys', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('9', 'Home & Kitchen', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('10', 'Sports & Fitness', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('11', 'Auto Accessories', '1', '', '', '', '', '', 'no-image.png', '0', '1', '0');
INSERT INTO `cd_category_new` VALUES ('12', 'Mobile', '1', '', '', '', '', '', 'no-image.png', '1', '1', '0');
INSERT INTO `cd_category_new` VALUES ('13', 'Mobile Accessories', '1', '', '', '', '', '', 'no-image.png', '1', '0', '0');
INSERT INTO `cd_category_new` VALUES ('14', 'Tablet', '1', '', '', '', '', '', 'no-image.png', '1', '0', '0');
INSERT INTO `cd_category_new` VALUES ('15', 'Tablet Accessories', '1', '', '', '', '', '', 'no-image.png', '1', '0', '0');
INSERT INTO `cd_category_new` VALUES ('16', 'Laptops', '1', '', '', '', '', '', 'no-image.png', '2', '0', '0');
INSERT INTO `cd_category_new` VALUES ('17', 'Laptop Accessories', '1', '', '', '', '', '', 'no-image.png', '2', '0', '0');
INSERT INTO `cd_category_new` VALUES ('18', 'Monitors (LED/LCD)', '1', '', '', '', '', '', 'no-image.png', '2', '0', '0');
INSERT INTO `cd_category_new` VALUES ('19', 'Computer Accessories', '1', '', '', '', '', '', 'no-image.png', '2', '0', '0');
INSERT INTO `cd_category_new` VALUES ('20', 'Printers & Scanners', '1', '', '', '', '', '', 'no-image.png', '2', '0', '0');
INSERT INTO `cd_category_new` VALUES ('21', 'Storage Devices', '1', '', '', '', '', '', 'no-image.png', '2', '0', '0');
INSERT INTO `cd_category_new` VALUES ('22', 'Softwares', '1', '', '', '', '', '', 'no-image.png', '2', '0', '0');
INSERT INTO `cd_category_new` VALUES ('23', 'Networking', '1', '', '', '', '', '', 'no-image.png', '2', '0', '0');
INSERT INTO `cd_category_new` VALUES ('24', 'Books', '1', '', '', '', '', '', 'no-image.png', '3', '0', '0');
INSERT INTO `cd_category_new` VALUES ('25', 'Educational', '1', '', '', '', '', '', 'no-image.png', '3', '0', '0');
INSERT INTO `cd_category_new` VALUES ('26', 'EBooks', '1', '', '', '', '', '', 'no-image.png', '3', '0', '0');
INSERT INTO `cd_category_new` VALUES ('27', 'Magazines', '1', '', '', '', '', '', 'no-image.png', '3', '0', '0');
INSERT INTO `cd_category_new` VALUES ('28', 'Stationery', '1', '', '', '', '', '', 'no-image.png', '3', '0', '0');
INSERT INTO `cd_category_new` VALUES ('29', 'TVs', '1', '', '', '', '', '', 'no-image.png', '4', '0', '0');
INSERT INTO `cd_category_new` VALUES ('30', 'DVD & Home Theaters', '1', '', '', '', '', '', 'no-image.png', '4', '0', '0');
INSERT INTO `cd_category_new` VALUES ('31', 'iPod & MP3 Players', '1', '', '', '', '', '', 'no-image.png', '4', '0', '0');
INSERT INTO `cd_category_new` VALUES ('32', 'Telephones', '1', '', '', '', '', '', 'no-image.png', '4', '0', '0');
INSERT INTO `cd_category_new` VALUES ('33', 'Gaming', '1', '', '', '', '', '', 'no-image.png', '4', '0', '0');
INSERT INTO `cd_category_new` VALUES ('34', 'Digital Cameras', '1', '', '', '', '', '', 'no-image.png', '5', '0', '0');
INSERT INTO `cd_category_new` VALUES ('35', 'Digital SLR', '1', '', '', '', '', '', 'no-image.png', '5', '0', '0');
INSERT INTO `cd_category_new` VALUES ('36', 'Digital Photo Frames', '1', '', '', '', '', '', 'no-image.png', '5', '0', '0');
INSERT INTO `cd_category_new` VALUES ('37', 'Camcorders', '1', '', '', '', '', '', 'no-image.png', '5', '0', '0');
INSERT INTO `cd_category_new` VALUES ('38', 'Binoculars', '1', '', '', '', '', '', 'no-image.png', '5', '0', '0');
INSERT INTO `cd_category_new` VALUES ('39', 'Telescopes', '1', '', '', '', '', '', 'no-image.png', '5', '0', '0');
INSERT INTO `cd_category_new` VALUES ('40', 'Lens', '1', '', '', '', '', '', 'no-image.png', '5', '0', '0');
INSERT INTO `cd_category_new` VALUES ('41', 'Memory Cards', '1', '', '', '', '', '', 'no-image.png', '5', '0', '0');
INSERT INTO `cd_category_new` VALUES ('42', 'Accessories', '1', '', '', '', '', '', 'no-image.png', '5', '0', '0');
INSERT INTO `cd_category_new` VALUES ('43', 'Cakes', '1', '', '', '', '', '', 'no-image.png', '6', '0', '0');
INSERT INTO `cd_category_new` VALUES ('44', 'Chocolates', '1', '', '', '', '', '', 'no-image.png', '6', '0', '0');
INSERT INTO `cd_category_new` VALUES ('45', 'Sweets', '1', '', '', '', '', '', 'no-image.png', '6', '0', '0');
INSERT INTO `cd_category_new` VALUES ('46', 'Dry Fruits', '1', '', '', '', '', '', 'no-image.png', '6', '0', '0');
INSERT INTO `cd_category_new` VALUES ('47', 'Flowers', '1', '', '', '', '', '', 'no-image.png', '6', '0', '0');
INSERT INTO `cd_category_new` VALUES ('48', 'Combo Gifts', '1', '', '', '', '', '', 'no-image.png', '6', '0', '0');
INSERT INTO `cd_category_new` VALUES ('49', 'Gift Ideas', '1', '', '', '', '', '', 'no-image.png', '6', '0', '0');
INSERT INTO `cd_category_new` VALUES ('50', 'Gift Vouchers', '1', '', '', '', '', '', 'no-image.png', '6', '0', '0');
INSERT INTO `cd_category_new` VALUES ('51', 'Fashion', '1', '', '', '', '', '', 'no-image.png', '7', '0', '0');
INSERT INTO `cd_category_new` VALUES ('52', 'Footwear', '1', '', '', '', '', '', 'no-image.png', '7', '0', '0');
INSERT INTO `cd_category_new` VALUES ('53', 'Eyewear', '1', '', '', '', '', '', 'no-image.png', '7', '0', '0');
INSERT INTO `cd_category_new` VALUES ('54', 'Clothing Accessories', '1', '', '', '', '', '', 'no-image.png', '7', '0', '0');
INSERT INTO `cd_category_new` VALUES ('55', 'Personal Care & Beauty', '1', '', '', '', '', '', 'no-image.png', '7', '0', '0');
INSERT INTO `cd_category_new` VALUES ('56', 'Jewellery', '1', '', '', '', '', '', 'no-image.png', '7', '0', '0');
INSERT INTO `cd_category_new` VALUES ('57', 'Watches', '1', '', '', '', '', '', 'no-image.png', '7', '0', '0');
INSERT INTO `cd_category_new` VALUES ('58', 'Travel & Bags', '1', '', '', '', '', '', 'no-image.png', '7', '0', '0');
INSERT INTO `cd_category_new` VALUES ('59', 'Baby Products', '1', '', '', '', '', '', 'no-image.png', '8', '0', '0');
INSERT INTO `cd_category_new` VALUES ('60', 'Kids Clothing', '1', '', '', '', '', '', 'no-image.png', '8', '0', '0');
INSERT INTO `cd_category_new` VALUES ('61', 'Toys & Games', '1', '', '', '', '', '', 'no-image.png', '8', '0', '0');
INSERT INTO `cd_category_new` VALUES ('62', 'Home Appliances', '1', '', '', '', '', '', 'no-image.png', '9', '0', '0');
INSERT INTO `cd_category_new` VALUES ('63', 'Home Furnishing', '1', '', '', '', '', '', 'no-image.png', '9', '0', '0');
INSERT INTO `cd_category_new` VALUES ('64', 'Home Decor', '1', '', '', '', '', '', 'no-image.png', '9', '0', '0');
INSERT INTO `cd_category_new` VALUES ('65', 'Kitchen Appliances', '1', '', '', '', '', '', 'no-image.png', '9', '0', '0');
INSERT INTO `cd_category_new` VALUES ('66', 'Kitchenware', '1', '', '', '', '', '', 'no-image.png', '9', '0', '0');
INSERT INTO `cd_category_new` VALUES ('67', 'Fitness', '1', '', '', '', '', '', 'no-image.png', '10', '0', '0');
INSERT INTO `cd_category_new` VALUES ('68', 'Team Sports', '1', '', '', '', '', '', 'no-image.png', '10', '0', '0');
INSERT INTO `cd_category_new` VALUES ('69', 'Racquet Sports', '1', '', '', '', '', '', 'no-image.png', '10', '0', '0');
INSERT INTO `cd_category_new` VALUES ('70', 'Outdoor and Adventure Gear', '1', '', '', '', '', '', 'no-image.png', '10', '0', '0');
INSERT INTO `cd_category_new` VALUES ('71', 'Other Sports', '1', '', '', '', '', '', 'no-image.png', '10', '0', '0');
INSERT INTO `cd_category_new` VALUES ('72', 'Car Accessories', '1', '', '', '', '', '', 'no-image.png', '11', '0', '0');
INSERT INTO `cd_category_new` VALUES ('73', 'Car Care & Cleaning', '1', '', '', '', '', '', 'no-image.png', '11', '0', '0');
INSERT INTO `cd_category_new` VALUES ('74', 'Car Utility', '1', '', '', '', '', '', 'no-image.png', '11', '0', '0');
INSERT INTO `cd_category_new` VALUES ('75', 'Car Audio Visual', '1', '', '', '', '', '', 'no-image.png', '11', '0', '0');
INSERT INTO `cd_category_new` VALUES ('76', 'Car Decor', '1', '', '', '', '', '', 'no-image.png', '11', '0', '0');
INSERT INTO `cd_category_new` VALUES ('77', 'Car Covers', '1', '', '', '', '', '', 'no-image.png', '11', '0', '0');
INSERT INTO `cd_category_new` VALUES ('78', 'Smartphones', '1', '', '', '', '', '', 'no-image.png', '12', '0', '0');
INSERT INTO `cd_category_new` VALUES ('79', 'Dual Sim', '1', '', '', '', '', '', 'no-image.png', '12', '0', '0');
INSERT INTO `cd_category_new` VALUES ('80', 'Android', '1', '', '', '', '', '', 'no-image.png', '12', '0', '0');
INSERT INTO `cd_category_new` VALUES ('81', 'Touch Screen', '1', '', '', '', '', '', 'no-image.png', '12', '0', '0');
INSERT INTO `cd_category_new` VALUES ('82', 'Windows', '1', '', '', '', '', '', 'no-image.png', '12', '0', '0');
INSERT INTO `cd_category_new` VALUES ('83', 'Budget Phones', '1', '', '', '', '', '', 'no-image.png', '12', '0', '0');
INSERT INTO `cd_category_new` VALUES ('84', 'Memory Cards', '1', '', '', '', '', '', 'no-image.png', '13', '0', '0');
INSERT INTO `cd_category_new` VALUES ('85', 'Bluetooth & Headsets', '1', '', '', '', '', '', 'no-image.png', '13', '0', '0');
INSERT INTO `cd_category_new` VALUES ('86', 'Featured Accessories', '1', '', '', '', '', '', 'no-image.png', '13', '0', '0');
INSERT INTO `cd_category_new` VALUES ('87', 'Covers & Cases', '1', '', '', '', '', '', 'no-image.png', '13', '0', '0');
INSERT INTO `cd_category_new` VALUES ('88', 'Calling', '1', '', '', '', '', '', 'no-image.png', '14', '0', '0');
INSERT INTO `cd_category_new` VALUES ('89', 'Android', '1', '', '', '', '', '', 'no-image.png', '14', '0', '0');
INSERT INTO `cd_category_new` VALUES ('90', 'Latest', '1', '', '', '', '', '', 'no-image.png', '14', '0', '0');
INSERT INTO `cd_category_new` VALUES ('91', 'Best Selling', '1', '', '', '', '', '', 'no-image.png', '14', '0', '0');
INSERT INTO `cd_category_new` VALUES ('92', 'Tablet carry cases', '1', '', '', '', '', '', 'no-image.png', '15', '0', '0');
INSERT INTO `cd_category_new` VALUES ('93', 'Other Tablet Accessories', '1', '', '', '', '', '', 'no-image.png', '15', '0', '0');
INSERT INTO `cd_category_new` VALUES ('94', 'Portable Netbooks', '1', '', '', '', '', '', 'no-image.png', '16', '0', '0');
INSERT INTO `cd_category_new` VALUES ('95', 'Gaming and Business Netbooks', '1', '', '', '', '', '', 'no-image.png', '16', '0', '0');
INSERT INTO `cd_category_new` VALUES ('96', 'Super Sleek Ultrabooks', '1', '', '', '', '', '', 'no-image.png', '16', '0', '0');
INSERT INTO `cd_category_new` VALUES ('97', 'Laptop Bags', '1', '', '', '', '', '', 'no-image.png', '17', '0', '0');
INSERT INTO `cd_category_new` VALUES ('98', 'Laptop Chargers', '1', '', '', '', '', '', 'no-image.png', '17', '0', '0');
INSERT INTO `cd_category_new` VALUES ('99', 'Laptop Batteries', '1', '', '', '', '', '', 'no-image.png', '17', '0', '0');
INSERT INTO `cd_category_new` VALUES ('100', 'Laptop Skins', '1', '', '', '', '', '', 'no-image.png', '17', '0', '0');
INSERT INTO `cd_category_new` VALUES ('101', 'Laptop HeadPhones', '1', '', '', '', '', '', 'no-image.png', '17', '0', '0');
INSERT INTO `cd_category_new` VALUES ('102', 'Monitors (LED/LCD)', '1', '', '', '', '', '', 'no-image.png', '18', '0', '0');
INSERT INTO `cd_category_new` VALUES ('103', 'Keyboards', '1', '', '', '', '', '', 'no-image.png', '19', '0', '0');
INSERT INTO `cd_category_new` VALUES ('104', 'Mouse', '1', '', '', '', '', '', 'no-image.png', '19', '0', '0');
INSERT INTO `cd_category_new` VALUES ('105', 'Webcams', '1', '', '', '', '', '', 'no-image.png', '19', '0', '0');
INSERT INTO `cd_category_new` VALUES ('106', 'Speakers', '1', '', '', '', '', '', 'no-image.png', '19', '0', '0');
INSERT INTO `cd_category_new` VALUES ('107', 'Ink Jet & Laser Jet', '1', '', '', '', '', '', 'no-image.png', '20', '0', '0');
INSERT INTO `cd_category_new` VALUES ('108', 'Cartridges', '1', '', '', '', '', '', 'no-image.png', '20', '0', '0');
INSERT INTO `cd_category_new` VALUES ('109', 'Scanners', '1', '', '', '', '', '', 'no-image.png', '20', '0', '0');
INSERT INTO `cd_category_new` VALUES ('110', 'All in One', '1', '', '', '', '', '', 'no-image.png', '20', '0', '0');
INSERT INTO `cd_category_new` VALUES ('111', 'Memory Cards', '1', '', '', '', '', '', 'no-image.png', '21', '0', '0');
INSERT INTO `cd_category_new` VALUES ('112', 'USB Drives', '1', '', '', '', '', '', 'no-image.png', '21', '0', '0');
INSERT INTO `cd_category_new` VALUES ('113', 'Hard Disc Drives', '1', '', '', '', '', '', 'no-image.png', '21', '0', '0');
INSERT INTO `cd_category_new` VALUES ('114', 'DVD Writers', '1', '', '', '', '', '', 'no-image.png', '21', '0', '0');
INSERT INTO `cd_category_new` VALUES ('115', 'Memory Card Readers', '1', '', '', '', '', '', 'no-image.png', '21', '0', '0');
INSERT INTO `cd_category_new` VALUES ('116', 'Antivirus & Security', '1', '', '', '', '', '', 'no-image.png', '22', '0', '0');
INSERT INTO `cd_category_new` VALUES ('117', 'Operating Systems', '1', '', '', '', '', '', 'no-image.png', '22', '0', '0');
INSERT INTO `cd_category_new` VALUES ('118', 'Games', '1', '', '', '', '', '', 'no-image.png', '22', '0', '0');
INSERT INTO `cd_category_new` VALUES ('119', 'Education & Reference', '1', '', '', '', '', '', 'no-image.png', '22', '0', '0');
INSERT INTO `cd_category_new` VALUES ('120', 'USB Data Cards', '1', '', '', '', '', '', 'no-image.png', '23', '0', '0');
INSERT INTO `cd_category_new` VALUES ('121', 'Routers', '1', '', '', '', '', '', 'no-image.png', '23', '0', '0');
INSERT INTO `cd_category_new` VALUES ('122', 'Cables & Connectors', '1', '', '', '', '', '', 'no-image.png', '23', '0', '0');
INSERT INTO `cd_category_new` VALUES ('123', 'Lan Cards', '1', '', '', '', '', '', 'no-image.png', '23', '0', '0');
INSERT INTO `cd_category_new` VALUES ('124', 'New Release', '1', '', '', '', '', '', 'no-image.png', '24', '0', '0');
INSERT INTO `cd_category_new` VALUES ('125', 'Bestseller', '1', '', '', '', '', '', 'no-image.png', '24', '0', '0');
INSERT INTO `cd_category_new` VALUES ('126', 'Boxsets', '1', '', '', '', '', '', 'no-image.png', '24', '0', '0');
INSERT INTO `cd_category_new` VALUES ('127', 'Indian Author', '1', '', '', '', '', '', 'no-image.png', '24', '0', '0');
INSERT INTO `cd_category_new` VALUES ('128', 'International Author', '1', '', '', '', '', '', 'no-image.png', '24', '0', '0');
INSERT INTO `cd_category_new` VALUES ('129', 'Literary Fiction', '1', '', '', '', '', '', 'no-image.png', '24', '0', '0');
INSERT INTO `cd_category_new` VALUES ('130', 'Kids Corner', '1', '', '', '', '', '', 'no-image.png', '24', '0', '0');
INSERT INTO `cd_category_new` VALUES ('131', 'Biographies', '1', '', '', '', '', '', 'no-image.png', '24', '0', '0');
INSERT INTO `cd_category_new` VALUES ('132', 'History', '1', '', '', '', '', '', 'no-image.png', '24', '0', '0');
INSERT INTO `cd_category_new` VALUES ('133', 'Competitive Exams', '1', '', '', '', '', '', 'no-image.png', '25', '0', '0');
INSERT INTO `cd_category_new` VALUES ('134', 'Academic', '1', '', '', '', '', '', 'no-image.png', '25', '0', '0');
INSERT INTO `cd_category_new` VALUES ('135', 'School Textbooks', '1', '', '', '', '', '', 'no-image.png', '25', '0', '0');
INSERT INTO `cd_category_new` VALUES ('136', 'Language Learning', '1', '', '', '', '', '', 'no-image.png', '25', '0', '0');
INSERT INTO `cd_category_new` VALUES ('137', 'Engineering Entrance', '1', '', '', '', '', '', 'no-image.png', '25', '0', '0');
INSERT INTO `cd_category_new` VALUES ('138', 'Engineering', '1', '', '', '', '', '', 'no-image.png', '26', '0', '0');
INSERT INTO `cd_category_new` VALUES ('139', 'Management', '1', '', '', '', '', '', 'no-image.png', '26', '0', '0');
INSERT INTO `cd_category_new` VALUES ('140', 'Science', '1', '', '', '', '', '', 'no-image.png', '26', '0', '0');
INSERT INTO `cd_category_new` VALUES ('141', 'Fiction', '1', '', '', '', '', '', 'no-image.png', '26', '0', '0');
INSERT INTO `cd_category_new` VALUES ('142', 'Automobile', '1', '', '', '', '', '', 'no-image.png', '27', '0', '0');
INSERT INTO `cd_category_new` VALUES ('143', 'Business', '1', '', '', '', '', '', 'no-image.png', '27', '0', '0');
INSERT INTO `cd_category_new` VALUES ('144', 'Lifestyle', '1', '', '', '', '', '', 'no-image.png', '27', '0', '0');
INSERT INTO `cd_category_new` VALUES ('145', 'Fashion', '1', '', '', '', '', '', 'no-image.png', '27', '0', '0');
INSERT INTO `cd_category_new` VALUES ('146', 'Film', '1', '', '', '', '', '', 'no-image.png', '27', '0', '0');
INSERT INTO `cd_category_new` VALUES ('147', 'Sports', '1', '', '', '', '', '', 'no-image.png', '27', '0', '0');
INSERT INTO `cd_category_new` VALUES ('148', 'Science', '1', '', '', '', '', '', 'no-image.png', '27', '0', '0');
INSERT INTO `cd_category_new` VALUES ('149', 'Advertising', '1', '', '', '', '', '', 'no-image.png', '27', '0', '0');
INSERT INTO `cd_category_new` VALUES ('150', 'Current Affairs', '1', '', '', '', '', '', 'no-image.png', '27', '0', '0');
INSERT INTO `cd_category_new` VALUES ('151', 'Pens and Pencils', '1', '', '', '', '', '', 'no-image.png', '28', '0', '0');
INSERT INTO `cd_category_new` VALUES ('152', 'Calculators', '1', '', '', '', '', '', 'no-image.png', '28', '0', '0');
INSERT INTO `cd_category_new` VALUES ('153', 'Diaries & Notebooks', '1', '', '', '', '', '', 'no-image.png', '28', '0', '0');
INSERT INTO `cd_category_new` VALUES ('154', 'Art Supplies', '1', '', '', '', '', '', 'no-image.png', '28', '0', '0');
INSERT INTO `cd_category_new` VALUES ('155', 'School Supplies', '1', '', '', '', '', '', 'no-image.png', '28', '0', '0');
INSERT INTO `cd_category_new` VALUES ('156', 'Office Supplies', '1', '', '', '', '', '', 'no-image.png', '28', '0', '0');
INSERT INTO `cd_category_new` VALUES ('157', 'LED TV', '1', '', '', '', '', '', 'no-image.png', '29', '0', '0');
INSERT INTO `cd_category_new` VALUES ('158', 'LCD TV', '1', '', '', '', '', '', 'no-image.png', '29', '0', '0');
INSERT INTO `cd_category_new` VALUES ('159', 'Plasma', '1', '', '', '', '', '', 'no-image.png', '29', '0', '0');
INSERT INTO `cd_category_new` VALUES ('160', 'DVD Players', '1', '', '', '', '', '', 'no-image.png', '30', '0', '0');
INSERT INTO `cd_category_new` VALUES ('161', 'Home Theaters', '1', '', '', '', '', '', 'no-image.png', '30', '0', '0');
INSERT INTO `cd_category_new` VALUES ('162', 'Speakers', '1', '', '', '', '', '', 'no-image.png', '30', '0', '0');
INSERT INTO `cd_category_new` VALUES ('163', 'Accessories & Supplies', '1', '', '', '', '', '', 'no-image.png', '30', '0', '0');
INSERT INTO `cd_category_new` VALUES ('164', 'Apple iPod', '1', '', '', '', '', '', 'no-image.png', '31', '0', '0');
INSERT INTO `cd_category_new` VALUES ('165', 'Players Accessories', '1', '', '', '', '', '', 'no-image.png', '31', '0', '0');
INSERT INTO `cd_category_new` VALUES ('166', 'Boomboxes', '1', '', '', '', '', '', 'no-image.png', '31', '0', '0');
INSERT INTO `cd_category_new` VALUES ('167', 'MP3 Players', '1', '', '', '', '', '', 'no-image.png', '31', '0', '0');
INSERT INTO `cd_category_new` VALUES ('168', 'Corded Phones', '1', '', '', '', '', '', 'no-image.png', '32', '0', '0');
INSERT INTO `cd_category_new` VALUES ('169', 'Cordless Phones', '1', '', '', '', '', '', 'no-image.png', '32', '0', '0');
INSERT INTO `cd_category_new` VALUES ('170', 'Fax Machines', '1', '', '', '', '', '', 'no-image.png', '32', '0', '0');
INSERT INTO `cd_category_new` VALUES ('171', 'Gaming Consoles', '1', '', '', '', '', '', 'no-image.png', '33', '0', '0');
INSERT INTO `cd_category_new` VALUES ('172', 'Gaming Media', '1', '', '', '', '', '', 'no-image.png', '33', '0', '0');
INSERT INTO `cd_category_new` VALUES ('173', 'Gaming Access', '1', '', '', '', '', '', 'no-image.png', '33', '0', '0');
INSERT INTO `cd_category_new` VALUES ('174', 'Camera Bags', '1', '', '', '', '', '', 'no-image.png', '42', '0', '0');
INSERT INTO `cd_category_new` VALUES ('175', 'Tripods', '1', '', '', '', '', '', 'no-image.png', '42', '0', '0');
INSERT INTO `cd_category_new` VALUES ('176', 'Camera Chargers', '1', '', '', '', '', '', 'no-image.png', '42', '0', '0');
INSERT INTO `cd_category_new` VALUES ('177', 'Camera Batteries', '1', '', '', '', '', '', 'no-image.png', '42', '0', '0');
INSERT INTO `cd_category_new` VALUES ('178', 'Camera Lenses', '1', '', '', '', '', '', 'no-image.png', '42', '0', '0');
INSERT INTO `cd_category_new` VALUES ('179', 'Camera Lense Filters', '1', '', '', '', '', '', 'no-image.png', '42', '0', '0');
INSERT INTO `cd_category_new` VALUES ('180', 'Flash Lights', '1', '', '', '', '', '', 'no-image.png', '42', '0', '0');
INSERT INTO `cd_category_new` VALUES ('181', 'Scratch Guards', '1', '', '', '', '', '', 'no-image.png', '42', '0', '0');
INSERT INTO `cd_category_new` VALUES ('182', 'Miscellaneous Accessories', '1', '', '', '', '', '', 'no-image.png', '42', '0', '0');
INSERT INTO `cd_category_new` VALUES ('183', 'Eggless', '1', '', '', '', '', '', 'no-image.png', '43', '0', '0');
INSERT INTO `cd_category_new` VALUES ('184', 'Blackforest', '1', '', '', '', '', '', 'no-image.png', '43', '0', '0');
INSERT INTO `cd_category_new` VALUES ('185', 'Chocoloate', '1', '', '', '', '', '', 'no-image.png', '43', '0', '0');
INSERT INTO `cd_category_new` VALUES ('186', 'Vanilla', '1', '', '', '', '', '', 'no-image.png', '43', '0', '0');
INSERT INTO `cd_category_new` VALUES ('187', 'Pineapple', '1', '', '', '', '', '', 'no-image.png', '43', '0', '0');
INSERT INTO `cd_category_new` VALUES ('188', 'Strawberry', '1', '', '', '', '', '', 'no-image.png', '43', '0', '0');
INSERT INTO `cd_category_new` VALUES ('189', 'Cheese', '1', '', '', '', '', '', 'no-image.png', '43', '0', '0');
INSERT INTO `cd_category_new` VALUES ('190', 'Tart', '1', '', '', '', '', '', 'no-image.png', '43', '0', '0');
INSERT INTO `cd_category_new` VALUES ('191', 'Dark Chocolates', '1', '', '', '', '', '', 'no-image.png', '44', '0', '0');
INSERT INTO `cd_category_new` VALUES ('192', 'Milk Chocolates', '1', '', '', '', '', '', 'no-image.png', '44', '0', '0');
INSERT INTO `cd_category_new` VALUES ('193', 'Chocolate Gift Box', '1', '', '', '', '', '', 'no-image.png', '44', '0', '0');
INSERT INTO `cd_category_new` VALUES ('194', 'Heart Shaped', '1', '', '', '', '', '', 'no-image.png', '44', '0', '0');
INSERT INTO `cd_category_new` VALUES ('195', 'Barfi', '1', '', '', '', '', '', 'no-image.png', '45', '0', '0');
INSERT INTO `cd_category_new` VALUES ('196', 'Halwa', '1', '', '', '', '', '', 'no-image.png', '45', '0', '0');
INSERT INTO `cd_category_new` VALUES ('197', 'Ladoo', '1', '', '', '', '', '', 'no-image.png', '45', '0', '0');
INSERT INTO `cd_category_new` VALUES ('198', 'Mango Sweets', '1', '', '', '', '', '', 'no-image.png', '45', '0', '0');
INSERT INTO `cd_category_new` VALUES ('199', 'Modak', '1', '', '', '', '', '', 'no-image.png', '45', '0', '0');
INSERT INTO `cd_category_new` VALUES ('200', 'Peda', '1', '', '', '', '', '', 'no-image.png', '45', '0', '0');
INSERT INTO `cd_category_new` VALUES ('201', 'Sugarfree Sweets', '1', '', '', '', '', '', 'no-image.png', '45', '0', '0');
INSERT INTO `cd_category_new` VALUES ('202', 'Kaju Sweets', '1', '', '', '', '', '', 'no-image.png', '45', '0', '0');
INSERT INTO `cd_category_new` VALUES ('203', 'Almonds', '1', '', '', '', '', '', 'no-image.png', '46', '0', '0');
INSERT INTO `cd_category_new` VALUES ('204', 'Cashews', '1', '', '', '', '', '', 'no-image.png', '46', '0', '0');
INSERT INTO `cd_category_new` VALUES ('205', 'Mix Dry Fruits', '1', '', '', '', '', '', 'no-image.png', '46', '0', '0');
INSERT INTO `cd_category_new` VALUES ('206', 'Pistas', '1', '', '', '', '', '', 'no-image.png', '46', '0', '0');
INSERT INTO `cd_category_new` VALUES ('207', 'Roses', '1', '', '', '', '', '', 'no-image.png', '47', '0', '0');
INSERT INTO `cd_category_new` VALUES ('208', 'Lilies', '1', '', '', '', '', '', 'no-image.png', '47', '0', '0');
INSERT INTO `cd_category_new` VALUES ('209', 'Gerberas', '1', '', '', '', '', '', 'no-image.png', '47', '0', '0');
INSERT INTO `cd_category_new` VALUES ('210', 'Carnations', '1', '', '', '', '', '', 'no-image.png', '47', '0', '0');
INSERT INTO `cd_category_new` VALUES ('211', 'Orchids', '1', '', '', '', '', '', 'no-image.png', '47', '0', '0');
INSERT INTO `cd_category_new` VALUES ('212', 'Flower Bunch', '1', '', '', '', '', '', 'no-image.png', '47', '0', '0');
INSERT INTO `cd_category_new` VALUES ('213', 'Flower Basket', '1', '', '', '', '', '', 'no-image.png', '47', '0', '0');
INSERT INTO `cd_category_new` VALUES ('214', 'Flower Arrangement', '1', '', '', '', '', '', 'no-image.png', '47', '0', '0');
INSERT INTO `cd_category_new` VALUES ('215', 'Gift Baskets', '1', '', '', '', '', '', 'no-image.png', '48', '0', '0');
INSERT INTO `cd_category_new` VALUES ('216', 'Gifts Hampers', '1', '', '', '', '', '', 'no-image.png', '48', '0', '0');
INSERT INTO `cd_category_new` VALUES ('217', 'Flowers with Cake', '1', '', '', '', '', '', 'no-image.png', '48', '0', '0');
INSERT INTO `cd_category_new` VALUES ('218', 'Flowers with Chocolates', '1', '', '', '', '', '', 'no-image.png', '48', '0', '0');
INSERT INTO `cd_category_new` VALUES ('219', 'Flowers with Teddy', '1', '', '', '', '', '', 'no-image.png', '48', '0', '0');
INSERT INTO `cd_category_new` VALUES ('220', 'Same Day Delivery', '1', '', '', '', '', '', 'no-image.png', '49', '0', '0');
INSERT INTO `cd_category_new` VALUES ('221', 'Every Hour & Day', '1', '', '', '', '', '', 'no-image.png', '49', '0', '0');
INSERT INTO `cd_category_new` VALUES ('222', 'Midnight Delivery', '1', '', '', '', '', '', 'no-image.png', '49', '0', '0');
INSERT INTO `cd_category_new` VALUES ('223', 'Gifts with freebies', '1', '', '', '', '', '', 'no-image.png', '49', '0', '0');
INSERT INTO `cd_category_new` VALUES ('224', 'Best Deals', '1', '', '', '', '', '', 'no-image.png', '49', '0', '0');
INSERT INTO `cd_category_new` VALUES ('225', 'Soft Toys', '1', '', '', '', '', '', 'no-image.png', '49', '0', '0');
INSERT INTO `cd_category_new` VALUES ('226', 'Apparel', '1', '', '', '', '', '', 'no-image.png', '50', '0', '0');
INSERT INTO `cd_category_new` VALUES ('227', 'Accessories', '1', '', '', '', '', '', 'no-image.png', '50', '0', '0');
INSERT INTO `cd_category_new` VALUES ('228', 'Watches', '1', '', '', '', '', '', 'no-image.png', '50', '0', '0');
INSERT INTO `cd_category_new` VALUES ('229', 'Jewellery', '1', '', '', '', '', '', 'no-image.png', '50', '0', '0');
INSERT INTO `cd_category_new` VALUES ('230', 'Bags', '1', '', '', '', '', '', 'no-image.png', '50', '0', '0');
INSERT INTO `cd_category_new` VALUES ('231', 'Food', '1', '', '', '', '', '', 'no-image.png', '50', '0', '0');
INSERT INTO `cd_category_new` VALUES ('232', 'Men\'s Clothing', '1', '', '', '', '', '', 'no-image.png', '51', '0', '0');
INSERT INTO `cd_category_new` VALUES ('233', 'Women\'s Clothing', '1', '', '', '', '', '', 'no-image.png', '51', '0', '0');
INSERT INTO `cd_category_new` VALUES ('234', 'Men', '1', '', '', '', '', '', 'no-image.png', '52', '0', '0');
INSERT INTO `cd_category_new` VALUES ('235', 'Women', '1', '', '', '', '', '', 'no-image.png', '52', '0', '0');
INSERT INTO `cd_category_new` VALUES ('236', 'Kids', '1', '', '', '', '', '', 'no-image.png', '52', '0', '0');
INSERT INTO `cd_category_new` VALUES ('237', 'Shoe Accessories', '1', '', '', '', '', '', 'no-image.png', '52', '0', '0');
INSERT INTO `cd_category_new` VALUES ('238', 'Sunglasses', '1', '', '', '', '', '', 'no-image.png', '53', '0', '0');
INSERT INTO `cd_category_new` VALUES ('239', 'Eyeglasses', '1', '', '', '', '', '', 'no-image.png', '53', '0', '0');
INSERT INTO `cd_category_new` VALUES ('240', 'Belts', '1', '', '', '', '', '', 'no-image.png', '54', '0', '0');
INSERT INTO `cd_category_new` VALUES ('241', 'Wallets & Clutches', '1', '', '', '', '', '', 'no-image.png', '54', '0', '0');
INSERT INTO `cd_category_new` VALUES ('242', 'Ties & Cuflinks', '1', '', '', '', '', '', 'no-image.png', '54', '0', '0');
INSERT INTO `cd_category_new` VALUES ('243', 'Socks & Handkerchiefs', '1', '', '', '', '', '', 'no-image.png', '54', '0', '0');
INSERT INTO `cd_category_new` VALUES ('244', 'Scarves', '1', '', '', '', '', '', 'no-image.png', '54', '0', '0');
INSERT INTO `cd_category_new` VALUES ('245', 'Mufflers & Stoles', '1', '', '', '', '', '', 'no-image.png', '54', '0', '0');
INSERT INTO `cd_category_new` VALUES ('246', 'Shawls', '1', '', '', '', '', '', 'no-image.png', '54', '0', '0');
INSERT INTO `cd_category_new` VALUES ('247', 'Perfumes & Deodorants', '1', '', '', '', '', '', 'no-image.png', '55', '0', '0');
INSERT INTO `cd_category_new` VALUES ('248', 'Shaving', '1', '', '', '', '', '', 'no-image.png', '55', '0', '0');
INSERT INTO `cd_category_new` VALUES ('249', 'FaceCare', '1', '', '', '', '', '', 'no-image.png', '55', '0', '0');
INSERT INTO `cd_category_new` VALUES ('250', 'SkinCare', '1', '', '', '', '', '', 'no-image.png', '55', '0', '0');
INSERT INTO `cd_category_new` VALUES ('251', 'HairCare', '1', '', '', '', '', '', 'no-image.png', '55', '0', '0');
INSERT INTO `cd_category_new` VALUES ('252', 'Lipstick & Nail Polish', '1', '', '', '', '', '', 'no-image.png', '55', '0', '0');
INSERT INTO `cd_category_new` VALUES ('253', 'Bracelets', '1', '', '', '', '', '', 'no-image.png', '56', '0', '0');
INSERT INTO `cd_category_new` VALUES ('254', 'Jewellery Sets', '1', '', '', '', '', '', 'no-image.png', '56', '0', '0');
INSERT INTO `cd_category_new` VALUES ('255', 'Chains', '1', '', '', '', '', '', 'no-image.png', '56', '0', '0');
INSERT INTO `cd_category_new` VALUES ('256', 'Earrings', '1', '', '', '', '', '', 'no-image.png', '56', '0', '0');
INSERT INTO `cd_category_new` VALUES ('257', 'Necklaces', '1', '', '', '', '', '', 'no-image.png', '56', '0', '0');
INSERT INTO `cd_category_new` VALUES ('258', 'Pendants', '1', '', '', '', '', '', 'no-image.png', '56', '0', '0');
INSERT INTO `cd_category_new` VALUES ('259', 'Rings', '1', '', '', '', '', '', 'no-image.png', '56', '0', '0');
INSERT INTO `cd_category_new` VALUES ('260', 'Men', '1', '', '', '', '', '', 'no-image.png', '57', '0', '0');
INSERT INTO `cd_category_new` VALUES ('261', 'Women', '1', '', '', '', '', '', 'no-image.png', '57', '0', '0');
INSERT INTO `cd_category_new` VALUES ('262', 'Kids Watches', '1', '', '', '', '', '', 'no-image.png', '57', '0', '0');
INSERT INTO `cd_category_new` VALUES ('263', 'Watches Gifts & Sets', '1', '', '', '', '', '', 'no-image.png', '57', '0', '0');
INSERT INTO `cd_category_new` VALUES ('264', 'Trolley Bags', '1', '', '', '', '', '', 'no-image.png', '58', '0', '0');
INSERT INTO `cd_category_new` VALUES ('265', 'Laptop Bags', '1', '', '', '', '', '', 'no-image.png', '58', '0', '0');
INSERT INTO `cd_category_new` VALUES ('266', 'Backpacks & Sling Bags', '1', '', '', '', '', '', 'no-image.png', '58', '0', '0');
INSERT INTO `cd_category_new` VALUES ('267', 'School Bags', '1', '', '', '', '', '', 'no-image.png', '58', '0', '0');
INSERT INTO `cd_category_new` VALUES ('268', 'Clothing & Shoes', '1', '', '', '', '', '', 'no-image.png', '59', '0', '0');
INSERT INTO `cd_category_new` VALUES ('269', 'Feeding & Nursing', '1', '', '', '', '', '', 'no-image.png', '59', '0', '0');
INSERT INTO `cd_category_new` VALUES ('270', 'Diapers & Wipes', '1', '', '', '', '', '', 'no-image.png', '59', '0', '0');
INSERT INTO `cd_category_new` VALUES ('271', 'Gear&Nursery', '1', '', '', '', '', '', 'no-image.png', '59', '0', '0');
INSERT INTO `cd_category_new` VALUES ('272', 'Skin & Health Care', '1', '', '', '', '', '', 'no-image.png', '59', '0', '0');
INSERT INTO `cd_category_new` VALUES ('273', 'Boys', '1', '', '', '', '', '', 'no-image.png', '60', '0', '0');
INSERT INTO `cd_category_new` VALUES ('274', 'Girls', '1', '', '', '', '', '', 'no-image.png', '60', '0', '0');
INSERT INTO `cd_category_new` VALUES ('275', 'Boys T-Shirt', '1', '', '', '', '', '', 'no-image.png', '60', '0', '0');
INSERT INTO `cd_category_new` VALUES ('276', 'Boys Shirts', '1', '', '', '', '', '', 'no-image.png', '60', '0', '0');
INSERT INTO `cd_category_new` VALUES ('277', 'Girls T-Shirt', '1', '', '', '', '', '', 'no-image.png', '60', '0', '0');
INSERT INTO `cd_category_new` VALUES ('278', 'Girls Tops', '1', '', '', '', '', '', 'no-image.png', '60', '0', '0');
INSERT INTO `cd_category_new` VALUES ('279', 'Girls Dress', '1', '', '', '', '', '', 'no-image.png', '60', '0', '0');
INSERT INTO `cd_category_new` VALUES ('280', 'Battery Operated', '1', '', '', '', '', '', 'no-image.png', '61', '0', '0');
INSERT INTO `cd_category_new` VALUES ('281', 'Dolls & Soft Toys', '1', '', '', '', '', '', 'no-image.png', '61', '0', '0');
INSERT INTO `cd_category_new` VALUES ('282', 'Board Games & Puzzles', '1', '', '', '', '', '', 'no-image.png', '61', '0', '0');
INSERT INTO `cd_category_new` VALUES ('283', 'Educational', '1', '', '', '', '', '', 'no-image.png', '61', '0', '0');
INSERT INTO `cd_category_new` VALUES ('284', 'Vehicles', '1', '', '', '', '', '', 'no-image.png', '61', '0', '0');
INSERT INTO `cd_category_new` VALUES ('285', 'Blocks', '1', '', '', '', '', '', 'no-image.png', '61', '0', '0');
INSERT INTO `cd_category_new` VALUES ('286', 'Washing Machines', '1', '', '', '', '', '', 'no-image.png', '62', '0', '0');
INSERT INTO `cd_category_new` VALUES ('287', 'Refrigeraters', '1', '', '', '', '', '', 'no-image.png', '62', '0', '0');
INSERT INTO `cd_category_new` VALUES ('288', 'Air Conditioners', '1', '', '', '', '', '', 'no-image.png', '62', '0', '0');
INSERT INTO `cd_category_new` VALUES ('289', 'Irons', '1', '', '', '', '', '', 'no-image.png', '62', '0', '0');
INSERT INTO `cd_category_new` VALUES ('290', 'Vacuum Clearners', '1', '', '', '', '', '', 'no-image.png', '62', '0', '0');
INSERT INTO `cd_category_new` VALUES ('291', 'Geysers', '1', '', '', '', '', '', 'no-image.png', '62', '0', '0');
INSERT INTO `cd_category_new` VALUES ('292', 'Room Heaters', '1', '', '', '', '', '', 'no-image.png', '62', '0', '0');
INSERT INTO `cd_category_new` VALUES ('293', 'Bed Sheets', '1', '', '', '', '', '', 'no-image.png', '63', '0', '0');
INSERT INTO `cd_category_new` VALUES ('294', 'Cushion & Covers', '1', '', '', '', '', '', 'no-image.png', '63', '0', '0');
INSERT INTO `cd_category_new` VALUES ('295', 'Blankets & Quilts', '1', '', '', '', '', '', 'no-image.png', '63', '0', '0');
INSERT INTO `cd_category_new` VALUES ('296', 'Curtains', '1', '', '', '', '', '', 'no-image.png', '63', '0', '0');
INSERT INTO `cd_category_new` VALUES ('297', 'Bean Bags', '1', '', '', '', '', '', 'no-image.png', '63', '0', '0');
INSERT INTO `cd_category_new` VALUES ('298', 'Bathroom Accessories', '1', '', '', '', '', '', 'no-image.png', '63', '0', '0');
INSERT INTO `cd_category_new` VALUES ('299', 'Vases', '1', '', '', '', '', '', 'no-image.png', '64', '0', '0');
INSERT INTO `cd_category_new` VALUES ('300', 'Flowers', '1', '', '', '', '', '', 'no-image.png', '64', '0', '0');
INSERT INTO `cd_category_new` VALUES ('301', 'Paintings', '1', '', '', '', '', '', 'no-image.png', '64', '0', '0');
INSERT INTO `cd_category_new` VALUES ('302', 'Wall Hangings', '1', '', '', '', '', '', 'no-image.png', '64', '0', '0');
INSERT INTO `cd_category_new` VALUES ('303', 'Pooja Items', '1', '', '', '', '', '', 'no-image.png', '64', '0', '0');
INSERT INTO `cd_category_new` VALUES ('304', 'Idols & Statues', '1', '', '', '', '', '', 'no-image.png', '64', '0', '0');
INSERT INTO `cd_category_new` VALUES ('305', 'Photo Frames', '1', '', '', '', '', '', 'no-image.png', '64', '0', '0');
INSERT INTO `cd_category_new` VALUES ('306', 'Wall Clocks', '1', '', '', '', '', '', 'no-image.png', '64', '0', '0');
INSERT INTO `cd_category_new` VALUES ('307', 'Microwaves', '1', '', '', '', '', '', 'no-image.png', '65', '0', '0');
INSERT INTO `cd_category_new` VALUES ('308', 'OTG', '1', '', '', '', '', '', 'no-image.png', '65', '0', '0');
INSERT INTO `cd_category_new` VALUES ('309', 'Pop UP Toaster', '1', '', '', '', '', '', 'no-image.png', '65', '0', '0');
INSERT INTO `cd_category_new` VALUES ('310', 'Sandwich Maker', '1', '', '', '', '', '', 'no-image.png', '65', '0', '0');
INSERT INTO `cd_category_new` VALUES ('311', 'Blenders', '1', '', '', '', '', '', 'no-image.png', '65', '0', '0');
INSERT INTO `cd_category_new` VALUES ('312', 'Food Processor', '1', '', '', '', '', '', 'no-image.png', '65', '0', '0');
INSERT INTO `cd_category_new` VALUES ('313', 'Mixer Grinder', '1', '', '', '', '', '', 'no-image.png', '65', '0', '0');
INSERT INTO `cd_category_new` VALUES ('314', 'Kitchen Tools', '1', '', '', '', '', '', 'no-image.png', '66', '0', '0');
INSERT INTO `cd_category_new` VALUES ('315', 'Barware', '1', '', '', '', '', '', 'no-image.png', '66', '0', '0');
INSERT INTO `cd_category_new` VALUES ('316', 'Cookers', '1', '', '', '', '', '', 'no-image.png', '66', '0', '0');
INSERT INTO `cd_category_new` VALUES ('317', 'Cookware', '1', '', '', '', '', '', 'no-image.png', '66', '0', '0');
INSERT INTO `cd_category_new` VALUES ('318', 'Mugs & Dinnerware', '1', '', '', '', '', '', 'no-image.png', '66', '0', '0');
INSERT INTO `cd_category_new` VALUES ('319', 'Stove & Cooktops', '1', '', '', '', '', '', 'no-image.png', '66', '0', '0');
INSERT INTO `cd_category_new` VALUES ('320', 'Containers', '1', '', '', '', '', '', 'no-image.png', '66', '0', '0');
INSERT INTO `cd_category_new` VALUES ('321', 'Fitness Accessories', '1', '', '', '', '', '', 'no-image.png', '67', '0', '0');
INSERT INTO `cd_category_new` VALUES ('322', 'Fitness Equipment', '1', '', '', '', '', '', 'no-image.png', '67', '0', '0');
INSERT INTO `cd_category_new` VALUES ('323', 'Golf', '1', '', '', '', '', '', 'no-image.png', '68', '0', '0');
INSERT INTO `cd_category_new` VALUES ('324', 'Cricket', '1', '', '', '', '', '', 'no-image.png', '68', '0', '0');
INSERT INTO `cd_category_new` VALUES ('325', 'Football', '1', '', '', '', '', '', 'no-image.png', '68', '0', '0');
INSERT INTO `cd_category_new` VALUES ('326', 'Basket Ball', '1', '', '', '', '', '', 'no-image.png', '68', '0', '0');
INSERT INTO `cd_category_new` VALUES ('327', 'Hockey', '1', '', '', '', '', '', 'no-image.png', '68', '0', '0');
INSERT INTO `cd_category_new` VALUES ('328', 'Badminton', '1', '', '', '', '', '', 'no-image.png', '69', '0', '0');
INSERT INTO `cd_category_new` VALUES ('329', 'Tennis', '1', '', '', '', '', '', 'no-image.png', '69', '0', '0');
INSERT INTO `cd_category_new` VALUES ('330', 'Table Tennis', '1', '', '', '', '', '', 'no-image.png', '69', '0', '0');
INSERT INTO `cd_category_new` VALUES ('331', 'Squash', '1', '', '', '', '', '', 'no-image.png', '69', '0', '0');
INSERT INTO `cd_category_new` VALUES ('332', 'Cycling', '1', '', '', '', '', '', 'no-image.png', '70', '0', '0');
INSERT INTO `cd_category_new` VALUES ('333', 'Camping and Hiking', '1', '', '', '', '', '', 'no-image.png', '70', '0', '0');
INSERT INTO `cd_category_new` VALUES ('334', 'Boxing', '1', '', '', '', '', '', 'no-image.png', '71', '0', '0');
INSERT INTO `cd_category_new` VALUES ('335', 'Skating', '1', '', '', '', '', '', 'no-image.png', '71', '0', '0');
INSERT INTO `cd_category_new` VALUES ('336', 'Swimming and Diving', '1', '', '', '', '', '', 'no-image.png', '71', '0', '0');
INSERT INTO `cd_category_new` VALUES ('337', 'Volley Ball', '1', '', '', '', '', '', 'no-image.png', '71', '0', '0');
INSERT INTO `cd_category_new` VALUES ('338', 'Mats', '1', '', '', '', '', '', 'no-image.png', '72', '0', '0');
INSERT INTO `cd_category_new` VALUES ('339', 'Sun Control', '1', '', '', '', '', '', 'no-image.png', '72', '0', '0');
INSERT INTO `cd_category_new` VALUES ('340', 'Sill Plates', '1', '', '', '', '', '', 'no-image.png', '72', '0', '0');
INSERT INTO `cd_category_new` VALUES ('341', 'Care Accessories', '1', '', '', '', '', '', 'no-image.png', '73', '0', '0');
INSERT INTO `cd_category_new` VALUES ('342', 'Cleaner & Shiner', '1', '', '', '', '', '', 'no-image.png', '73', '0', '0');
INSERT INTO `cd_category_new` VALUES ('343', 'Polish & Wax', '1', '', '', '', '', '', 'no-image.png', '73', '0', '0');
INSERT INTO `cd_category_new` VALUES ('344', 'Mobile Charger', '1', '', '', '', '', '', 'no-image.png', '74', '0', '0');
INSERT INTO `cd_category_new` VALUES ('345', 'Key Chains', '1', '', '', '', '', '', 'no-image.png', '74', '0', '0');
INSERT INTO `cd_category_new` VALUES ('346', 'Dash Mat', '1', '', '', '', '', '', 'no-image.png', '74', '0', '0');
INSERT INTO `cd_category_new` VALUES ('347', 'Speakers', '1', '', '', '', '', '', 'no-image.png', '75', '0', '0');
INSERT INTO `cd_category_new` VALUES ('348', 'CD Players', '1', '', '', '', '', '', 'no-image.png', '75', '0', '0');
INSERT INTO `cd_category_new` VALUES ('349', 'Amplifiers', '1', '', '', '', '', '', 'no-image.png', '75', '0', '0');
INSERT INTO `cd_category_new` VALUES ('350', 'Perfume', '1', '', '', '', '', '', 'no-image.png', '76', '0', '0');
INSERT INTO `cd_category_new` VALUES ('351', 'Rain Visor', '1', '', '', '', '', '', 'no-image.png', '76', '0', '0');
INSERT INTO `cd_category_new` VALUES ('352', 'Tissue Box', '1', '', '', '', '', '', 'no-image.png', '76', '0', '0');
INSERT INTO `cd_category_new` VALUES ('353', 'Body Covers', '1', '', '', '', '', '', 'no-image.png', '77', '0', '0');
INSERT INTO `cd_category_new` VALUES ('354', 'Steering Covers', '1', '', '', '', '', '', 'no-image.png', '77', '0', '0');
INSERT INTO `cd_category_new` VALUES ('355', 'Tees & Polos', '1', '', '', '', '', '', 'no-image.png', '232', '0', '0');
INSERT INTO `cd_category_new` VALUES ('356', 'Shirts', '1', '', '', '', '', '', 'no-image.png', '232', '0', '0');
INSERT INTO `cd_category_new` VALUES ('357', 'Denims', '1', '', '', '', '', '', 'no-image.png', '232', '0', '0');
INSERT INTO `cd_category_new` VALUES ('358', 'Activewear', '1', '', '', '', '', '', 'no-image.png', '232', '0', '0');
INSERT INTO `cd_category_new` VALUES ('359', 'Winter Wear', '1', '', '', '', '', '', 'no-image.png', '232', '0', '0');
INSERT INTO `cd_category_new` VALUES ('360', 'Trousers', '1', '', '', '', '', '', 'no-image.png', '232', '0', '0');
INSERT INTO `cd_category_new` VALUES ('361', 'Tees & Vests', '1', '', '', '', '', '', 'no-image.png', '233', '0', '0');
INSERT INTO `cd_category_new` VALUES ('362', 'Fashion Tops', '1', '', '', '', '', '', 'no-image.png', '233', '0', '0');
INSERT INTO `cd_category_new` VALUES ('363', 'Jeans', '1', '', '', '', '', '', 'no-image.png', '233', '0', '0');
INSERT INTO `cd_category_new` VALUES ('364', 'Dresses', '1', '', '', '', '', '', 'no-image.png', '233', '0', '0');
INSERT INTO `cd_category_new` VALUES ('365', 'Ethnicwear', '1', '', '', '', '', '', 'no-image.png', '233', '0', '0');
INSERT INTO `cd_category_new` VALUES ('366', 'Lingerie-Innerwear', '1', '', '', '', '', '', 'no-image.png', '233', '0', '0');
INSERT INTO `cd_category_new` VALUES ('367', 'Shorts & Skirts', '1', '', '', '', '', '', 'no-image.png', '233', '0', '0');
INSERT INTO `cd_category_new` VALUES ('368', 'Sports Shoes', '1', '', '', '', '', '', 'no-image.png', '234', '0', '0');
INSERT INTO `cd_category_new` VALUES ('369', 'Casual Shoes', '1', '', '', '', '', '', 'no-image.png', '234', '0', '0');
INSERT INTO `cd_category_new` VALUES ('370', 'Formal Shoes', '1', '', '', '', '', '', 'no-image.png', '234', '0', '0');
INSERT INTO `cd_category_new` VALUES ('371', 'Slippers & FlipFlops', '1', '', '', '', '', '', 'no-image.png', '234', '0', '0');
INSERT INTO `cd_category_new` VALUES ('372', 'Sandals', '1', '', '', '', '', '', 'no-image.png', '234', '0', '0');
INSERT INTO `cd_category_new` VALUES ('373', 'Sandals & Bellerinas', '1', '', '', '', '', '', 'no-image.png', '235', '0', '0');
INSERT INTO `cd_category_new` VALUES ('374', 'Party & Bridal', '1', '', '', '', '', '', 'no-image.png', '235', '0', '0');
INSERT INTO `cd_category_new` VALUES ('375', 'Slippers & FlipFlops', '1', '', '', '', '', '', 'no-image.png', '235', '0', '0');
INSERT INTO `cd_category_new` VALUES ('376', 'Sports Shoes', '1', '', '', '', '', '', 'no-image.png', '235', '0', '0');
INSERT INTO `cd_category_new` VALUES ('377', 'Slippers/FlipFlops', '1', '', '', '', '', '', 'no-image.png', '236', '0', '0');
INSERT INTO `cd_category_new` VALUES ('378', 'Shoes Bags/Boxes', '1', '', '', '', '', '', 'no-image.png', '236', '0', '0');
INSERT INTO `cd_category_new` VALUES ('379', 'Socks', '1', '', '', '', '', '', 'no-image.png', '237', '0', '0');
INSERT INTO `cd_category_new` VALUES ('380', 'Foot Massager', '1', '', '', '', '', '', 'no-image.png', '237', '0', '0');
INSERT INTO `cd_category_new` VALUES ('381', 'Sports Watches', '1', '', '', '', '', '', 'no-image.png', '260', '0', '0');
INSERT INTO `cd_category_new` VALUES ('382', 'Fashion Watches', '1', '', '', '', '', '', 'no-image.png', '260', '0', '0');
INSERT INTO `cd_category_new` VALUES ('383', 'Luxury Watches', '1', '', '', '', '', '', 'no-image.png', '260', '0', '0');
INSERT INTO `cd_category_new` VALUES ('384', 'Sports Watches', '1', '', '', '', '', '', 'no-image.png', '261', '0', '0');
INSERT INTO `cd_category_new` VALUES ('385', 'Fashion Watches', '1', '', '', '', '', '', 'no-image.png', '261', '0', '0');
INSERT INTO `cd_category_new` VALUES ('386', 'Luxury Watches', '1', '', '', '', '', '', 'no-image.png', '261', '0', '0');
INSERT INTO `cd_category_new` VALUES ('387', 'Inner and sleep Wear', '1', '', '', '', '', '', 'no-image.png', '232', '0', '0');
INSERT INTO `cd_category_new` VALUES ('388', 'sarees', '1', '', '', '', '', '', 'no-image.png', '233', '0', '0');
INSERT INTO `cd_category_new` VALUES ('389', 'Gloves', '1', '', '', '', '', '', 'no-image.png', '54', '0', '0');
