<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
*/
if(SITE_FOR_LIVE)///For live site
{
    $config['base_url']    = "http://www.acumencs.com/jobshoppa/";
}
else
{
	$config['base_url']		=	"http://192.168.1.107/jobshoppa/";
}
$config['template_hints']		=	FALSE;// true=Enable Template Hints,   false=disable Template Hints // By Pritam Biswas
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
//$config['index_page'] = "index.php";//sh
$config['index_page'] = "";//sh working
/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of "AUTO" works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
if(SITE_FOR_LIVE)///For live site
{
    $config['uri_protocol']	= "ORIG_PATH_INFO";
}
else
{
	$config['uri_protocol']	= "PATH_INFO";
}
/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = "";
/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= "english";
/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = "UTF-8";
/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the "hooks" feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;
/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';
/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/

//$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-=';
$config['permitted_uri_chars'] = '';
/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string "words" that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] 	= 'c';
$config['function_trigger'] 	= 'm';
$config['directory_trigger'] 	= 'd'; // experimental not currently in use
/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------

|
| If you have enabled error logging, you can set an error threshold to 
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0; 
/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/logs/ folder.  Use a full server path with trailing slash.
|
*/

$config['log_path'] = '';
/*

|--------------------------------------------------------------------------

| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*

|--------------------------------------------------------------------------

| Cache Directory Path

|--------------------------------------------------------------------------

|

| Leave this BLANK unless you would like to set something other than the default

| system/cache/ folder.  Use a full server path with trailing slash.

|

*/

$config['cache_path'] = '';



/*

|--------------------------------------------------------------------------

| Encryption Key

|--------------------------------------------------------------------------

|

| If you use the Encryption class or the Sessions class with encryption

| enabled you MUST set an encryption key.  See the user guide for info.

|

*/

$config['encryption_key'] = "";



/*

|--------------------------------------------------------------------------

| Session Variables

|--------------------------------------------------------------------------

|

| 'session_cookie_name' = the name you want for the cookie

| 'encrypt_sess_cookie' = TRUE/FALSE (boolean).  Whether to encrypt the cookie

| 'session_expiration'  = the number of SECONDS you want the session to last.

|  by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.

| 'time_to_update'		= how many seconds between CI refreshing Session Information

|

*/

$config['sess_cookie_name']		= 'ci_session';

$config['sess_expiration']		= 7200;

$config['sess_encrypt_cookie']	= FALSE;

$config['sess_use_database']	= FALSE;

$config['sess_table_name']		= 'ci_sessions';

$config['sess_match_ip']		= FALSE;

$config['sess_match_useragent']	= TRUE;

$config['sess_time_to_update'] 	= 300;



/*

|--------------------------------------------------------------------------

| Cookie Related Variables

|--------------------------------------------------------------------------

|

| 'cookie_prefix' = Set a prefix if you need to avoid collisions

| 'cookie_domain' = Set to .your-domain.com for site-wide cookies

| 'cookie_path'   =  Typically will be a forward slash

|

*/

$config['cookie_prefix']	= "";

$config['cookie_domain']	= "";

$config['cookie_path']		= "/";



/*

|--------------------------------------------------------------------------

| Global XSS Filtering

|--------------------------------------------------------------------------

|

| Determines whether the XSS filter is always active when GET, POST or

| COOKIE data is encountered

|

*/

$config['global_xss_filtering'] = FALSE;



/*

|--------------------------------------------------------------------------

| Output Compression

|--------------------------------------------------------------------------

|

| Enables Gzip output compression for faster page loads.  When enabled,

| the output class will test whether your server supports Gzip.

| Even if it does, however, not all browsers support compression

| so enable only if you are reasonably sure your visitors can handle it.

|

| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it

| means you are prematurely outputting something to your browser. It could

| even be a line of whitespace at the end of one of your scripts.  For

| compression to work, nothing can be sent before the output buffer is called

| by the output class.  Do not "echo" any values with compression enabled.

|

*/

$config['compress_output'] = FALSE;



/*

|--------------------------------------------------------------------------

| Master Time Reference

|--------------------------------------------------------------------------

|

| Options are "local" or "gmt".  This pref tells the system whether to use

| your server's local time as the master "now" reference, or convert it to

| GMT.  See the "date helper" page of the user guide for information

| regarding date handling.

|

*/

$config['time_reference'] = 'local';





/*

|--------------------------------------------------------------------------

| Rewrite PHP Short Tags

|--------------------------------------------------------------------------

|

| If your PHP installation does not have short tag support enabled CI

| can rewrite the tags on-the-fly, enabling you to utilize that syntax

| in your view files.  Options are TRUE or FALSE (boolean)

|

*/

$config['rewrite_short_tags'] = FALSE;





/*

|--------------------------------------------------------------------------

| Reverse Proxy IPs

|--------------------------------------------------------------------------

|

| If your server is behind a reverse proxy, you must whitelist the proxy IP

| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR

| header in order to properly identify the visitor's IP address.

| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'

|

*/

$config['proxy_ips'] = '';





/*********Customized from here***********/

$config['images_url']    =    $config['base_url']."images/";

$config['css_url']       =    $config['base_url']."css/";

$config['js_url']        =    $config['base_url']."js/";



$config['admin_base_url']        =    $config['base_url']."admin/";

$config['agent_base_url']        =    $config['base_url']."agent/";



if(SITE_FOR_LIVE)///For live site

{

    $config['uri_seg']=4;///Used for pagination in get_admin_pagination(),Changed for live
	$config['fe_uri_seg']=3;///Used for pagination in get_fe_pagination(),Changed for live
}
else
{
    $config['uri_seg']=4;///Used for pagination in get_admin_pagination(),Changed for live
	$config['fe_uri_seg']=3;///Used for pagination in get_fe_pagination(),Changed for live
}
$config['security_salt']="_acu_";///for encrypting Password

//$config['site_date_format'] = 'd-m-Y H:i:s';
$config['site_date_format'] = 'd/m/Y';  
$config['front_job_date_format'] = 'd/m/Y, H:i';

$config['last_log_date_format'] = 'm-d-Y H:i:s';  

$config['front_date_format'] = 'M d, Y';

$config['front_db_date_format'] = 'd-M-Y';

// used in newsletter send//
$config['newsletter_date_format'] = 'd-M-Y';

// Default Currency//
$config['default_currency'] = '&#163;'; // added by iman

/*********added by Iman 14 Sep 2011***************/
$config['show_delete_in_list']=FALSE;
$config['show_deleted_records']=FALSE;
/*********end added by Iman 14 Sep 2011***************/

/*********For Commenting Created By and Created on by Iman 14 Sep 2011***************/
$config['show_createdby_records']=FALSE;

/*********added by Iman 14 Sep 2011***************/
$config['show_all_records']=FALSE;


/****    for recaptcha during registration ****/

$config['recaptcha_private_key'] = "6LfC88gSAAAAAP_9vck-7JlEx6gz5IzQhxWXW5oj";
$config['recaptcha_public_key']	="6LfC88gSAAAAAO2J7lo91pEgVje83SWy29brEsml";



/********** Language *************/
/* xml that contains translations */
$config['multilanguage_xml'] = 'multilanguage/tmx.xml';

/* cache of serialized TranslationContainer object that contains translations */
$config['multilanguage_object'] = 'multilanguage/translations.tc';


$config['default_language'] = 'en';
$config['languages'] = array('en', 'fr');

/********* end of language *********/



/******** Paypal ****/
$config['paypal_url'] = 'https://www.sandbox.paypal.com/cgi-bin/webscr';
$config['paypal_business_id']  = 'acumen@gmail.com';

/********************* File Upload config for job***************************************/

$config['job_file_upload_max_size']=15*1024;///for File upload
$config['job_file_upload_path'] = BASEPATH.'../uploaded/job/';
$config['job_file_upload_thumb_path'] = $config['job_file_upload_path'].'thumb/';

$config['job_photo_upload_thumb_height']=100;
$config['job_photo_upload_thumb_width']=80;

/********************* End File Upload config ***********************************/

/********************* File Upload config for credentials***************************************/

$config['credentials_file_upload_max_size']=15*1024;///for File upload
$config['credentials_file_upload_path'] = BASEPATH.'../uploaded/credentials/';
/********************* End File Upload config ***********************************/

////////	USER PROFILE IMAGE UPLOAD SETTINGS  /////////

$config['user_profile_image_upload_path']=BASEPATH.'../uploaded/user/';   
$config['user_profile_image_thumb_upload_path']=$config['user_profile_image_upload_path'].'thumb/';  
$config['user_profile_image_path']=$config['base_url']."uploaded/user/";   
$config['user_profile_image_thumb_path']=$config['user_profile_image_path']."thumb/";    

$config['user_profile_photo_upload_thumb_height']=75;
$config['user_profile_photo_upload_thumb_width']=100;

//////////////////////// end profile image upload settings ///////////////////////////





/* 20-10-2011 

TRADESMAN ALBUM IMAGE UPLOAD SETTINGS */
$config['image_file_upload_max_size']=10*1024;///image File upload
$config['trades_album_image_upload_path']=BASEPATH.'../uploaded/gallery/';   
$config['trades_album_image_thumb_upload_path']=$config['trades_album_image_upload_path'].'thumb/'; 

$config['trades_album_image_path']=$config['base_url']."uploaded/gallery/";   
$config['trades_album_image_thumb_path']=$config['trades_album_image_path']."thumb/";     

$config['trades_album_image_upload_thumb_height']=110;
$config['trades_album_image_upload_thumb_width']=110;


                                              
////////    MANAGE BLOG IMAGE UPLOAD SETTINGS  /////////

$config['manage_blog_image_upload_path']=BASEPATH.'../uploaded/blog/';   
$config['manage_blog_image_thumb_upload_path']=$config['manage_blog_image_upload_path'].'thumb/';  
$config['manage_blog_image_path']=$config['base_url']."uploaded/blog/";   
$config['manage_blog_image_thumb_path']=$config['manage_blog_image_path']."thumb/";    

$config['manage_blog_photo_upload_thumb_width'] = 110;
$config['manage_blog_photo_upload_thumb_height']=110;

//////////////////////// end MANAGE BLOG image upload settings ///////////////////////////


//////////////////////// HOME-PAGE IMAGE UPLOAD SETTINGS ///////////////////////////

$config['admin_banner_image_upload_path']=FCPATH.'uploaded/banner/';///for Banner image upload
$config['admin_banner_image_thumb_upload_path']=$config['admin_banner_image_upload_path'].'thumb/';///for Banner image upload
$config['banner_image_path']=$config['base_url']."uploaded/banner/";    ///for Banner image display
$config['banner_image_thumb_path']=$config['banner_image_path']."thumb/";    ///for Banner image display

$config['admin_banner_image_upload_thumb_height']=300;
$config['admin_banner_image_upload_thumb_width']=460;

/* default */
$config['admin_image_upload_thumb_height']=300;
$config['admin_image_upload_thumb_width']=460;

//////////////////////// end Home-Page image upload settings ///////////////////////////


/* Facebook */
$config['facebook_app_id'] = '323531874331876';
$config['facebook_sekret_key']  = 'e1bf74326620b4ed6ed0b0f20ad302f5';




/* invoice pdf file save path */
$config['ATTACHMENT_PDF_PATH']=BASEPATH."../uploaded/invoice/";  

/* mail body */

$config['EMAILBODYHTML']=BASEPATH.'../uploaded/mail_body/';

/// Newsletter max email setting
$config['max_email_allowed_in_newsletter'] = 20;


$config['day_allowed_to_approve_quote'] = 5;// mrinmoy  ## used in cron setting for quote_approve_day_expire

$config['quoteurjob_admin_url']="acumen.testing01@gmail.com";


$config['CONF_EMAIL_ID']="";
$config['MAIL_FROM_NAME']="";

//$config['quoteurjob_admin_url']="mrinsss@gmail.com";  // for testing


/* End of file config.php */

/* Location: ./system/application/config/config.php */

